import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-dim': '#131313',
        'primary-fixed': '#dae2ff',
        'error-container': '#93000a',
        'tertiary-container': '#3d0d00',
        'on-background': '#e5e2e1',
        tertiary: '#ffb59d',
        'surface-container-highest': '#353535',
        'secondary-container': '#8d04ee',
        'surface-container-low': '#1b1c1c',
        'on-primary': '#182e60',
        'on-tertiary': '#561f0b',
        'on-error': '#690005',
        'inverse-primary': '#495d92',
        outline: '#8f909a',
        'on-primary-container': '#7184bc',
        primary: '#b2c5ff',
        'surface-bright': '#393939',
        secondary: '#ddb8ff',
        'on-secondary-fixed': '#2c0051',
        'on-error-container': '#ffdad6',
        'surface-variant': '#353535',
        'on-tertiary-fixed-variant': '#72351f',
        error: '#ffb4ab',
        'on-primary-fixed': '#001848',
        'primary-fixed-dim': '#b2c5ff',
        'tertiary-fixed': '#ffdbd0',
        'on-primary-fixed-variant': '#314578',
        'on-secondary-container': '#ecd3ff',
        'surface-container-high': '#2a2a2a',
        'inverse-on-surface': '#303030',
        'primary-container': '#001a4d',
        'tertiary-fixed-dim': '#ffb59d',
        surface: '#131313',
        'on-secondary-fixed-variant': '#6800b3',
        'secondary-fixed': '#f0dbff',
        'on-surface': '#e5e2e1',
        'secondary-fixed-dim': '#ddb8ff',
        'inverse-surface': '#e5e2e1',
        'on-surface-variant': '#c5c6d1',
        'on-secondary': '#490080',
        'on-tertiary-fixed': '#390c00',
        'surface-tint': '#b2c5ff',
        'surface-container-lowest': '#0e0e0e',
        'surface-container': '#1f2020',
        background: '#131313',
        'outline-variant': '#44464f',
        'on-tertiary-container': '#bf7158',
        'sentiment-positive': '#4ade80',
        'sentiment-negative': '#f87171',
        'sentiment-warning': '#fb923c',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '48px',
        sm: '12px',
        margin: '32px',
        xs: '4px',
        xl: '80px',
        gutter: '24px',
        base: '8px',
        md: '24px',
      },
      fontFamily: {
        'headline-md': ['Montserrat'],
        'label-sm': ['DM Sans'],
        'display-lg': ['Montserrat'],
        'headline-lg': ['Montserrat'],
        'label-md': ['DM Sans'],
        'body-md': ['Inter'],
        'body-lg': ['Inter'],
        'table-data': ['Inter'],
        'label-caps': ['DM Sans'],
        'display-metrics': ['Montserrat'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '1.2', fontWeight: '700' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'table-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'display-metrics': ['36px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [forms, containerQueries],
}
